#!/usr/bin/env python3
"""
rebuild_wsop_project_pipeline.py

Rebuilds the WSOP project processed CSVs and chart files from the two Kaggle source datasets.

Core raw inputs:
  1) wsop_main_event_results_1971-2025.csv
     Columns expected: year, place, name, prize, city, state, country, entries, prizepool, buyin, start, finish

  2) wsop_main_event_final_table_2001-2025.csv
     Columns expected: year, entrants, place, name, prize

Optional researched label inputs:
  3) wsop_champion_eventtime_labels_reviewable.csv
  4) wsop_headsup_eventtime_labels_reviewable.csv

Important:
  - The two Kaggle datasets generate the economics panel, reconciliation outputs, heads-up bases,
    headline metrics, chart inputs, and most visualization outputs.
  - Pro/amateur/uncertain labels are NOT present in Kaggle. Those fields require the optional
    researched/reviewable label files.
  - The simulation output is synthetic and generated by code, not derived from Kaggle.

Example:
  python rebuild_wsop_project_pipeline.py \
    --results data/raw/wsop_main_event_results_1971-2025.csv \
    --final-table data/raw/wsop_main_event_final_table_2001-2025.csv \
    --champion-labels data/labels/wsop_champion_eventtime_labels_reviewable.csv \
    --headsup-labels data/labels/wsop_headsup_eventtime_labels_reviewable.csv \
    --output-root .
"""

from __future__ import annotations

import argparse
import re
import unicodedata
from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd


def normalize_name(value) -> str | float:
    """Normalize player names for joins/reconciliation without claiming identity certainty."""
    if pd.isna(value):
        return np.nan
    value = str(value)
    value = unicodedata.normalize("NFKD", value).encode("ascii", "ignore").decode("ascii")
    value = value.lower()
    value = re.sub(r"[^a-z0-9]+", "", value)
    return value


def era(year: int) -> str:
    """Tournament-era bucket used for interpretation."""
    year = int(year)
    if year <= 1995:
        return "Early Era (<=1995)"
    if year <= 2003:
        return "Pre-Boom (1996-2003)"
    if year <= 2006:
        return "Poker Boom (2004-2006)"
    return "Post-Boom (2007+)"


def require_columns(df: pd.DataFrame, required: list[str], dataset_name: str) -> None:
    missing = [c for c in required if c not in df.columns]
    if missing:
        raise ValueError(f"{dataset_name} missing required columns: {missing}")


def prior_main_event_cashes(results_df: pd.DataFrame, player_key: str, year: int) -> int:
    """Count prior rows in full Main Event results for the same normalized player."""
    return int(((results_df["player_key"].eq(player_key)) & (results_df["year"].lt(int(year)))).sum())


def safe_read_csv(path: Optional[str | Path]) -> Optional[pd.DataFrame]:
    if path is None:
        return None
    path = Path(path)
    if not path.exists():
        return None
    return pd.read_csv(path)


def write_csv(df: pd.DataFrame, path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(path, index=False)


def build_reconciliation(results: pd.DataFrame, final_table: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Compare overlapping final-table rows between the two Kaggle source datasets.

    The final-table dataset contains top-nine rows by year. The full-results dataset also contains
    placement rows for those same years/places, except where missing/special cases exist.
    """
    max_place = int(final_table["place"].max())
    min_year = int(final_table["year"].min())
    max_year = int(final_table["year"].max())

    results_overlap = results.loc[
        results["year"].between(min_year, max_year) & results["place"].le(max_place),
        ["year", "place", "name", "player_key", "prize", "entries"],
    ].copy()

    final_overlap = final_table[
        ["year", "entrants", "place", "name", "player_key", "prize"]
    ].copy()

    recon = final_overlap.merge(
        results_overlap,
        on=["year", "place"],
        how="outer",
        suffixes=("_final_table", "_results"),
        indicator=True,
    )

    recon["name_exact_match"] = recon["name_final_table"].eq(recon["name_results"])
    recon["name_normalized_match"] = recon["player_key_final_table"].eq(recon["player_key_results"])

    recon["prize_diff"] = recon["prize_final_table"] - recon["prize_results"]
    recon["prize_exact_match"] = recon["prize_diff"].fillna(np.inf).eq(0)

    recon["entrant_count_exact_match"] = recon["entrants"].eq(recon["entries"])

    # Backward-compatible aliases used in the current notebook.
    recon["name_match"] = recon["name_normalized_match"]
    recon["prize_match"] = recon["prize_exact_match"]
    recon["entrants_match"] = recon["entrant_count_exact_match"]

    recon_detail_cols = [
        "year",
        "entrants",
        "place",
        "name_final_table",
        "prize_final_table",
        "player_key_final_table",
        "name_results",
        "player_key_results",
        "prize_results",
        "entries",
        "_merge",
        "name_exact_match",
        "name_normalized_match",
        "name_match",
        "prize_diff",
        "prize_exact_match",
        "prize_match",
        "entrant_count_exact_match",
        "entrants_match",
    ]

    recon_detail = recon[recon_detail_cols].sort_values(["year", "place"]).reset_index(drop=True)
    matched = recon_detail.loc[recon_detail["_merge"].eq("both")].copy()

    all_shared_exact = (
        matched["name_exact_match"]
        & matched["prize_exact_match"]
        & matched["entrant_count_exact_match"]
    )

    summary = pd.DataFrame(
        [
            {"metric": "final_table_rows", "value": int(len(final_table))},
            {"metric": "results_rows_same_years_places", "value": int(len(results_overlap))},
            {"metric": "matched_rows_on_year_place", "value": int(len(matched))},
            {"metric": "final_table_only_rows", "value": int(recon_detail["_merge"].eq("left_only").sum())},
            {"metric": "results_only_rows", "value": int(recon_detail["_merge"].eq("right_only").sum())},
            {"metric": "name_exact_mismatch_rows_on_matched_records", "value": int((~matched["name_exact_match"]).sum())},
            {"metric": "name_normalized_mismatch_rows_on_matched_records", "value": int((~matched["name_normalized_match"]).sum())},
            {"metric": "prize_difference_rows_on_matched_records", "value": int((~matched["prize_exact_match"]).sum())},
            {"metric": "entrant_count_difference_rows_on_matched_records", "value": int((~matched["entrant_count_exact_match"]).sum())},
            {"metric": "all_shared_fields_exact_match_rows", "value": int(all_shared_exact.sum())},
            # Backward-compatible names used in your current notebook/report:
            {"metric": "final_table_rows_2001_2025_top9", "value": int(len(final_table))},
            {"metric": "results_rows_2001_2025_top9", "value": int(len(results_overlap))},
            {"metric": "matched_rows", "value": int(len(matched))},
            {"metric": "name_variant_rows_on_matched_records", "value": int((~matched["name_normalized_match"]).sum())},
        ]
    )

    return recon_detail, summary


def build_champion_labels(
    results: pd.DataFrame,
    final_table: pd.DataFrame,
    champion_label_source: Optional[pd.DataFrame],
    labels_dir: Path,
) -> pd.DataFrame:
    """Create champion label output from place=1 rows plus optional researched label layer."""
    champ_rows = results.loc[
        results["place"].eq(1),
        ["year", "name", "player_key", "place", "prize", "buyin", "entries"],
    ].copy()

    champ_rows = champ_rows.rename(
        columns={
            "name": "player_name",
            "place": "finish",
            "prize": "prize_usd",
            "buyin": "buyin_usd",
        }
    )
    champ_rows["source_file"] = "results"

    # Add 2020 champion from final table if full results lacks 2020.
    if 2020 not in set(champ_rows["year"]):
        ft_2020 = final_table.loc[(final_table["year"].eq(2020)) & (final_table["place"].eq(1))].copy()
        if not ft_2020.empty:
            add = pd.DataFrame(
                {
                    "year": ft_2020["year"].values,
                    "player_name": ft_2020["name"].values,
                    "player_key": ft_2020["player_key"].values,
                    "finish": ft_2020["place"].values,
                    "prize_usd": ft_2020["prize"].values,
                    "buyin_usd": 10000,
                    "entries": ft_2020["entrants"].values,
                    "source_file": "final_table",
                }
            )
            champ_rows = pd.concat([champ_rows, add], ignore_index=True)

    champ_rows["prior_main_event_cashes"] = champ_rows.apply(
        lambda r: prior_main_event_cashes(results, r["player_key"], r["year"]),
        axis=1,
    )

    base_cols = [
        "year",
        "player_name",
        "finish",
        "status_at_event",
        "status_basis",
        "confidence",
        "evidence_note",
        "prior_main_event_cashes",
        "prize_usd",
        "buyin_usd",
        "entries",
        "source_file",
    ]

    if champion_label_source is None:
        skeleton = champ_rows.copy()
        skeleton["status_at_event"] = ""
        skeleton["status_basis"] = ""
        skeleton["confidence"] = ""
        skeleton["evidence_note"] = ""
        skeleton = skeleton[base_cols].sort_values(["year", "finish"])
        write_csv(skeleton, labels_dir / "wsop_champion_eventtime_labels_reviewable.csv")
        print("Wrote champion reviewable skeleton; labels must be filled to create final labeled output.")
        return skeleton

    manual = champion_label_source.copy()
    require_columns(
        manual,
        ["year", "player_name", "status_at_event", "status_basis", "confidence", "evidence_note"],
        "champion label source",
    )
    manual["player_key"] = manual["player_name"].map(normalize_name)

    manual_core = manual[
        ["year", "player_key", "status_at_event", "status_basis", "confidence", "evidence_note"]
    ].drop_duplicates(["year", "player_key"])

    out = champ_rows.merge(manual_core, on=["year", "player_key"], how="left")

    missing = out.loc[out["status_at_event"].isna(), ["year", "player_name"]]
    if not missing.empty:
        skeleton = out.copy()
        for col in ["status_at_event", "status_basis", "confidence", "evidence_note"]:
            skeleton[col] = skeleton[col].fillna("")
        skeleton = skeleton[base_cols].sort_values(["year", "finish"])
        write_csv(skeleton, labels_dir / "wsop_champion_eventtime_labels_reviewable_NEEDS_REVIEW.csv")
        raise ValueError(
            "Missing champion labels. Wrote NEEDS_REVIEW file. Missing rows:\n"
            + missing.to_string(index=False)
        )

    out = out[base_cols].sort_values(["year", "finish"]).reset_index(drop=True)
    return out


def build_yearly_economics(results: pd.DataFrame, champion_labels: pd.DataFrame) -> pd.DataFrame:
    """Build year-level economics panel from full-results data and join champion status."""
    yearly_base = (
        results.groupby("year", as_index=False)
        .agg(entries=("entries", "max"), buyin=("buyin", "max"), prize_pool=("prizepool", "max"))
    )

    winners = (
        results.loc[results["place"].eq(1), ["year", "name", "player_key", "prize"]]
        .rename(columns={"name": "winner_name", "player_key": "winner_key", "prize": "winner_prize"})
    )

    yearly = yearly_base.merge(winners, on="year", how="left")
    yearly["winner_share_pct"] = (yearly["winner_prize"] / yearly["prize_pool"]) * 100
    yearly["rake_pct"] = (1 - (yearly["prize_pool"] / (yearly["entries"] * yearly["buyin"]))) * 100
    yearly["rake_pct"] = yearly["rake_pct"].round(2)
    yearly["winner_roi_pct"] = ((yearly["winner_prize"] - yearly["buyin"]) / yearly["buyin"]) * 100
    yearly["era"] = yearly["year"].map(era)

    status = champion_labels[["year", "status_at_event", "status_basis", "confidence", "prior_main_event_cashes"]].copy()
    yearly = yearly.merge(status, on="year", how="left")

    ordered = [
        "year", "entries", "buyin", "prize_pool", "winner_name", "winner_prize", "winner_key",
        "winner_share_pct", "rake_pct", "winner_roi_pct", "era", "status_at_event",
        "status_basis", "confidence", "prior_main_event_cashes",
    ]
    return yearly[ordered].sort_values("year").reset_index(drop=True)


def build_headsup_labels(
    results: pd.DataFrame,
    final_table: pd.DataFrame,
    headsup_label_source: Optional[pd.DataFrame],
    labels_dir: Path,
) -> pd.DataFrame:
    """Build current 2001-2025 heads-up labels from final-table source plus researched label layer."""
    heads = final_table.loc[
        final_table["place"].isin([1, 2]),
        ["year", "name", "player_key", "place", "prize", "entrants"],
    ].copy()

    heads = heads.rename(
        columns={
            "name": "player_name",
            "place": "finish",
            "prize": "prize_usd",
            "entrants": "entries",
        }
    )
    heads["source_file"] = "final_table"
    heads["prior_main_event_cashes"] = heads.apply(
        lambda r: prior_main_event_cashes(results, r["player_key"], r["year"]),
        axis=1,
    )

    base_cols = [
        "year",
        "player_name",
        "finish",
        "status_at_event",
        "status_basis",
        "confidence",
        "evidence_note",
        "prior_main_event_cashes",
        "prize_usd",
        "entries",
        "source_file",
    ]

    if headsup_label_source is None:
        skeleton = heads.copy()
        skeleton["status_at_event"] = ""
        skeleton["status_basis"] = ""
        skeleton["confidence"] = ""
        skeleton["evidence_note"] = ""
        skeleton = skeleton[base_cols].sort_values(["year", "finish"])
        write_csv(skeleton, labels_dir / "wsop_headsup_eventtime_labels_reviewable.csv")
        print("Wrote heads-up reviewable skeleton; labels must be filled to create final labeled output.")
        return skeleton

    manual = headsup_label_source.copy()
    require_columns(
        manual,
        ["year", "player_name", "finish", "status_at_event", "status_basis", "confidence", "evidence_note"],
        "heads-up label source",
    )
    manual["player_key"] = manual["player_name"].map(normalize_name)
    manual_core = manual[
        ["year", "finish", "player_key", "status_at_event", "status_basis", "confidence", "evidence_note"]
    ].drop_duplicates(["year", "finish", "player_key"])

    out = heads.merge(manual_core, on=["year", "finish", "player_key"], how="left")

    missing = out.loc[out["status_at_event"].isna(), ["year", "finish", "player_name"]]
    if not missing.empty:
        skeleton = out.copy()
        for col in ["status_at_event", "status_basis", "confidence", "evidence_note"]:
            skeleton[col] = skeleton[col].fillna("")
        skeleton = skeleton[base_cols].sort_values(["year", "finish"])
        write_csv(skeleton, labels_dir / "wsop_headsup_eventtime_labels_reviewable_NEEDS_REVIEW.csv")
        raise ValueError(
            "Missing heads-up labels. Wrote NEEDS_REVIEW file. Missing rows:\n"
            + missing.to_string(index=False)
        )

    return out[base_cols].sort_values(["year", "finish"]).reset_index(drop=True)


def build_expanded_headsup_from_full_results(results: pd.DataFrame) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build a broader champion-runner-up base from the full-results dataset.

    This proves the pre-2001 expansion is possible where place 1 and place 2 exist.
    It does not label those older runner-ups as pro/amateur unless a label layer is added.
    """
    top2 = results.loc[
        results["place"].isin([1, 2]),
        ["year", "place", "name", "player_key", "prize", "entries", "buyin", "prizepool"],
    ].copy()

    coverage = (
        top2.groupby("year", as_index=False)
        .agg(
            top2_rows=("place", "size"),
            distinct_top2_places=("place", "nunique"),
            places_present=("place", lambda s: ",".join(map(str, sorted(s.unique())))),
        )
    )

    # More reliable than flattening MultiIndex blind: build champion/runner rows explicitly.
    champions = top2.loc[top2["place"].eq(1)].rename(
        columns={
            "name": "champion_name",
            "player_key": "champion_key",
            "prize": "champion_prize",
            "entries": "entries",
            "buyin": "buyin",
            "prizepool": "prize_pool",
        }
    )[["year", "champion_name", "champion_key", "champion_prize", "entries", "buyin", "prize_pool"]]

    runners = top2.loc[top2["place"].eq(2)].rename(
        columns={"name": "runner_up_name", "player_key": "runner_up_key", "prize": "runner_up_prize"}
    )[["year", "runner_up_name", "runner_up_key", "runner_up_prize"]]

    base = champions.merge(runners, on="year", how="left")
    base["has_runner_up"] = base["runner_up_name"].notna()
    base = base.sort_values("year").reset_index(drop=True)

    return coverage, base


def build_summary_outputs(yearly: pd.DataFrame, champion_labels: pd.DataFrame, heads_up_labels: pd.DataFrame) -> dict[str, pd.DataFrame]:
    era_summary = (
        yearly.groupby(["era", "status_at_event"], as_index=False)
        .size()
        .rename(columns={"size": "champion_results"})
        .sort_values(["era", "status_at_event"])
    )

    heads_up_pivot = (
        heads_up_labels
        .pivot_table(index="year", columns="finish", values="status_at_event", aggfunc="first")
        .rename(columns={1: "champion_status", 2: "runner_up_status"})
        .reset_index()
    )
    heads_up_pivot["heads_up_mix"] = heads_up_pivot["champion_status"] + " vs " + heads_up_pivot["runner_up_status"]

    heads_up_mix_counts = (
        heads_up_pivot.groupby("heads_up_mix", as_index=False)
        .size()
        .rename(columns={"size": "years"})
        .sort_values("years", ascending=False)
    )

    def champion_share_under_assumption(uncertain_as: str) -> pd.Series:
        labels = champion_labels["status_at_event"].replace({"Uncertain-Crossover": uncertain_as})
        counts = labels.value_counts()
        total = int(counts.sum())
        return pd.Series(
            {
                "uncertain_as": uncertain_as,
                "pro_count": int(counts.get("Pro", 0)),
                "amateur_count": int(counts.get("Amateur", 0)),
                "total": total,
                "pro_share": counts.get("Pro", 0) / total,
                "amateur_share": counts.get("Amateur", 0) / total,
            }
        )

    uncertainty = pd.DataFrame(
        [
            champion_share_under_assumption("Pro"),
            champion_share_under_assumption("Amateur"),
        ]
    )

    key_metrics = pd.DataFrame(
        [
            {
                "years_covered": f"{int(yearly['year'].min())}-{int(yearly['year'].max())}",
                "years_in_panel": int(len(yearly)),
                "max_entries_year": int(yearly.loc[yearly["entries"].idxmax(), "year"]),
                "max_entries": int(yearly["entries"].max()),
                "latest_year": int(yearly["year"].max()),
                "latest_entries": int(yearly.loc[yearly["year"].idxmax(), "entries"]),
                "latest_winner_share_pct": float(yearly.loc[yearly["year"].idxmax(), "winner_share_pct"]),
                "latest_estimated_rake_pct": float(yearly.loc[yearly["year"].idxmax(), "rake_pct"]),
            }
        ]
    )

    return {
        "wsop_era_champion_status_summary.csv": era_summary,
        "wsop_headsup_mix_by_year.csv": heads_up_pivot,
        "wsop_headsup_mix_counts.csv": heads_up_mix_counts,
        "wsop_uncertainty_stress_test.csv": uncertainty,
        "wsop_key_metrics.csv": key_metrics,
    }


def build_simulated_player_cohort(seed: int = 42, n: int = 5000) -> pd.DataFrame:
    """Generate synthetic player cohort for skill/variance section."""
    np.random.seed(seed)
    skill = np.random.beta(2, 8, n)
    entries = np.clip(np.random.negative_binomial(2, 0.3, n) + 1, 1, 40)

    base_cash_rate = 0.15
    cash_rate = np.clip(base_cash_rate + (skill - skill.mean()) * 0.3, 0.01, 0.60)
    cashes = np.random.binomial(entries, cash_rate)

    avg_buyin = 10_000
    ev_mult = 0.85 + skill * 4.0
    simulated_return = ev_mult * avg_buyin * cashes
    total_invested = entries * avg_buyin
    roi_pct = ((simulated_return - total_invested) / total_invested) * 100
    realized_cash_rate = (cashes / entries) * 100

    sim = pd.DataFrame(
        {
            "skill_pct": skill * 100,
            "entries": entries,
            "cash_rate": cash_rate * 100,
            "cashes": cashes,
            "realized_cash_rate": realized_cash_rate,
            "roi_pct": roi_pct,
        }
    )
    sim["entries_bin"] = pd.cut(
        sim["entries"],
        bins=[0, 1, 3, 7, 15, 40],
        labels=["1", "2-3", "4-7", "8-15", "16+"],
    )
    return sim


def make_charts(output_root: Path, yearly: pd.DataFrame, champion_labels: pd.DataFrame, heads_up_mix_counts: pd.DataFrame, sim_players: pd.DataFrame) -> None:
    """
    Generate the notebook's interactive Plotly HTML charts from processed data.
    PNG export is attempted only if kaleido is available.
    """
    try:
        import plotly.graph_objects as go
        import plotly.io as pio
        from scipy import stats
    except Exception as exc:
        print(f"Skipping chart generation because plotly/scipy import failed: {exc}")
        return

    charts_dir = output_root / "outputs" / "charts"
    charts_dir.mkdir(parents=True, exist_ok=True)

    pio.templates["custom_dark"] = go.layout.Template(
        layout=go.Layout(
            paper_bgcolor="#171614",
            plot_bgcolor="#1c1b19",
            font=dict(color="#cdccca", family="Arial, sans-serif"),
            colorway=["#19D3F3", "#EF553B", "#00CC96", "#7A9EAF", "#AB63FA", "#FFA15A"],
            xaxis=dict(gridcolor="#5c5b59", linecolor="#5c5b59", zerolinecolor="#5c5b59"),
            yaxis=dict(gridcolor="#5c5b59", linecolor="#5c5b59", zerolinecolor="#5c5b59"),
            margin=dict(l=70, r=40, t=120, b=80),
        )
    )
    pio.templates.default = "custom_dark"

    era_colors = {
        "Early Era (<=1995)": "#19D3F3",
        "Pre-Boom (1996-2003)": "#7A9EAF",
        "Poker Boom (2004-2006)": "#EF553B",
        "Post-Boom (2007+)": "#2CA25F",
    }
    palette = ["#636EFA", "#EF553B", "#00CC96", "#AB63FA", "#FFA15A"]

    def save_plot(fig, stem: str):
        fig.write_html(charts_dir / f"{stem}.html", include_plotlyjs="cdn")
        try:
            fig.write_image(charts_dir / f"{stem}.png", scale=2)
        except Exception:
            # png requires kaleido; HTML is enough for GitHub/project reproduction.
            pass

    # Figure 1
    fig1 = go.Figure()
    for e in ["Early Era (<=1995)", "Pre-Boom (1996-2003)", "Poker Boom (2004-2006)", "Post-Boom (2007+)"]:
        grp = yearly.loc[yearly["era"].eq(e)]
        fig1.add_trace(go.Scatter(x=grp["year"], y=grp["entries"], mode="markers+lines", name=e,
                                  marker=dict(size=8), line=dict(width=3, color=era_colors[e])))
    fig1.update_layout(title=dict(text="WSOP Main Event Field Size (1971-2025)<br><span style='font-size:14px;font-weight:normal;color:#9a9896;'>Source: yearly economics panel</span>"),
                       legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5))
    fig1.update_xaxes(title_text="Year", dtick=5)
    fig1.update_yaxes(title_text="Entries")
    save_plot(fig1, "field_size_trend")

    # Figure 2
    fig2 = go.Figure()
    fig2.add_trace(go.Scatter(x=yearly["year"], y=yearly["winner_share_pct"], mode="lines+markers",
                              fill="tozeroy", fillcolor="rgba(99, 110, 250, 0.35)",
                              line=dict(width=3), marker=dict(size=7), name="Winner Share %"))
    fig2.update_layout(title=dict(text="Winner's Prize Pool Share % (1971-2025)<br><span style='font-size:14px;font-weight:normal;color:#9a9896;'>Source: winner prize divided by total prize pool</span>"),
                       showlegend=False)
    fig2.update_xaxes(title_text="Year", dtick=5)
    fig2.update_yaxes(title_text="Winner Share %")
    save_plot(fig2, "winner_share_trend")

    # Figure 3
    rake_years = yearly.loc[yearly["year"] >= 2004].copy()
    fig3 = go.Figure()
    fig3.add_trace(go.Bar(x=rake_years["year"].astype(str), y=rake_years["rake_pct"], name="Rake %", marker_color="#EF553B"))
    fig3.update_layout(title=dict(text="WSOP Rake % by Year (2004-2025)<br><span style='font-size:14px;font-weight:normal;color:#9a9896;'>Source: estimated as 1 - prize_pool / (entries x buy-in)</span>"),
                       showlegend=False)
    fig3.update_xaxes(title_text="Year", tickangle=45)
    fig3.update_yaxes(title_text="Rake %")
    save_plot(fig3, "rake_percentage")

    # Figure 4
    status_colors = {"Pro": "#19D3F3", "Amateur": "#EF553B", "Uncertain-Crossover": "#FFA15A"}
    status_to_y = {"Amateur": 0, "Uncertain-Crossover": 1, "Pro": 2}
    champion_plot = champion_labels.copy()
    champion_plot["y"] = champion_plot["status_at_event"].map(status_to_y)
    fig4 = go.Figure()
    for status in ["Pro", "Amateur", "Uncertain-Crossover"]:
        sub = champion_plot.loc[champion_plot["status_at_event"].eq(status)]
        if sub.empty:
            continue
        fig4.add_trace(go.Scatter(
            x=sub["year"], y=sub["y"], mode="markers", name=status,
            marker=dict(size=11, color=status_colors[status], line=dict(width=1, color="white")),
            text=sub["player_name"],
            customdata=np.stack([sub["confidence"], sub["status_basis"], sub["evidence_note"]], axis=-1),
            hovertemplate="<b>%{text}</b><br>Year: %{x}<br>Status: " + status + "<br>Confidence: %{customdata[0]}<br>Basis: %{customdata[1]}<br>Note: %{customdata[2]}<extra></extra>",
        ))
    fig4.update_layout(title=dict(text="Champion Status at Time of Win (1971-2025)<br><span style='font-size:14px;font-weight:normal;color:#9a9896;'>Event-time classification with confidence notes</span>"),
                       legend=dict(orientation="h", yanchor="bottom", y=1.02, xanchor="center", x=0.5))
    fig4.update_xaxes(title_text="Year", dtick=5)
    fig4.update_yaxes(title_text="Status", tickmode="array", tickvals=[0, 1, 2],
                      ticktext=["Amateur", "Uncertain-Crossover", "Pro"], range=[-0.45, 2.45])
    save_plot(fig4, "champion_status_timeline")

    # Figure 5
    mix_plot = heads_up_mix_counts.copy()
    mix_plot["heads_up_mix_display"] = mix_plot["heads_up_mix"].replace({
        "Uncertain-Crossover vs Pro": "Uncertain vs Pro",
        "Pro vs Uncertain-Crossover": "Pro vs Uncertain",
    })
    fig5 = go.Figure()
    fig5.add_trace(go.Bar(x=mix_plot["heads_up_mix_display"], y=mix_plot["years"],
                          marker_color="#00CC96", text=mix_plot["years"], textposition="outside", name="Years"))
    fig5.update_layout(title=dict(text="Heads-Up Finalist Mix by Year Count (2001-2025)<br><span style='font-size:14px;font-weight:normal;color:#9a9896;'>Champion status and runner-up status grouped into matchup types</span>"),
                       showlegend=False)
    fig5.update_xaxes(title_text="Heads-Up Mix", tickangle=0)
    fig5.update_yaxes(title_text="Years")
    save_plot(fig5, "heads_up_mix_counts")

    # Figure 6
    order = ["1", "2-3", "4-7", "8-15", "16+"]
    sim_players = sim_players.copy()
    sim_players["entries_bin"] = pd.Categorical(sim_players["entries_bin"].astype(str), categories=order, ordered=True)
    fig6 = go.Figure()
    for i, b in enumerate(order):
        sub = sim_players.loc[sim_players["entries_bin"].eq(b), "roi_pct"]
        fig6.add_trace(go.Box(y=sub, name=f"{b} entries", marker_color=palette[i], boxmean=True))
    fig6.update_layout(title=dict(text="ROI Distribution by # Tournaments Played<br><span style='font-size:14px;font-weight:normal;color:#797876;'>Source: simulated cohort (n=5,000)</span>"),
                       legend=dict(orientation="h", yanchor="top", y=-0.22, xanchor="center", x=0.5))
    fig6.update_xaxes(title_text="Entries Bin")
    fig6.update_yaxes(title_text="Lifetime ROI %")
    save_plot(fig6, "simulated_roi_by_volume")

    # Figure 7
    sample = sim_players.sample(min(700, len(sim_players)), random_state=99)
    fig7 = go.Figure()
    for i, b in enumerate(order):
        sub = sample.loc[sample["entries_bin"].eq(b)]
        fig7.add_trace(go.Scatter(x=sub["skill_pct"], y=sub["realized_cash_rate"], mode="markers",
                                  name=f"{b} entries", marker=dict(color=palette[i], size=6, opacity=0.75)))
    m, bcoef, *_ = stats.linregress(sample["skill_pct"], sample["realized_cash_rate"])
    x_r = np.linspace(sample["skill_pct"].min(), sample["skill_pct"].max(), 100)
    fig7.add_trace(go.Scatter(x=x_r, y=m * x_r + bcoef, mode="lines", name="OLS Trend",
                              line=dict(color="white", width=2, dash="dash"), showlegend=True))
    fig7.update_traces(cliponaxis=False)
    fig7.update_layout(title=dict(text="Skill Percentile vs. ITM Cash Rate (n=700 sample)<br><span style='font-size:14px;font-weight:normal;color:#797876;'>Source: simulated cohort</span>"),
                       legend=dict(orientation="h", yanchor="top", y=-0.22, xanchor="center", x=0.5))
    fig7.update_xaxes(title_text="Skill %ile")
    fig7.update_yaxes(title_text="Cash Rate %")
    save_plot(fig7, "skill_vs_cash_rate")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--results", required=True, help="Path to Kaggle full-results CSV")
    parser.add_argument("--final-table", required=True, help="Path to Kaggle final-table CSV")
    parser.add_argument("--champion-labels", default=None, help="Optional champion reviewable/final label CSV")
    parser.add_argument("--headsup-labels", default=None, help="Optional heads-up reviewable/final label CSV")
    parser.add_argument("--output-root", default=".", help="Project root where data/ and outputs/ folders are written")
    parser.add_argument("--skip-charts", action="store_true")
    args = parser.parse_args()

    output_root = Path(args.output_root)
    data_dir = output_root / "data"
    raw_dir = data_dir / "raw"
    labels_dir = data_dir / "labels"
    processed_dir = data_dir / "processed"
    for d in [raw_dir, labels_dir, processed_dir]:
        d.mkdir(parents=True, exist_ok=True)

    results = pd.read_csv(args.results)
    final_table = pd.read_csv(args.final_table)

    require_columns(results, ["year", "place", "name", "prize", "entries", "prizepool", "buyin"], "full-results Kaggle dataset")
    require_columns(final_table, ["year", "entrants", "place", "name", "prize"], "final-table Kaggle dataset")

    # Keep raw copies inside project.
    write_csv(results, raw_dir / "wsop_main_event_results_1971-2025.csv")
    write_csv(final_table, raw_dir / "wsop_main_event_final_table_2001-2025.csv")

    results = results.copy()
    final_table = final_table.copy()
    results["player_key"] = results["name"].map(normalize_name)
    final_table["player_key"] = final_table["name"].map(normalize_name)

    # A) Reconciliation from the two Kaggle datasets.
    recon_detail, recon_summary = build_reconciliation(results, final_table)
    write_csv(recon_detail, processed_dir / "wsop_dataset_reconciliation_detail.csv")
    write_csv(recon_summary, processed_dir / "wsop_dataset_reconciliation_summary.csv")

    # B) Label-dependent files.
    champion_label_source = safe_read_csv(args.champion_labels)
    headsup_label_source = safe_read_csv(args.headsup_labels)

    if args.champion_labels:
        # Keep a copy of the reviewable/final source labels.
        write_csv(champion_label_source, labels_dir / "wsop_champion_eventtime_labels_reviewable.csv")

    if args.headsup_labels:
        write_csv(headsup_label_source, labels_dir / "wsop_headsup_eventtime_labels_reviewable.csv")

    champion_labels = build_champion_labels(results, final_table, champion_label_source, labels_dir)
    write_csv(champion_labels, labels_dir / "wsop_champion_eventtime_labels.csv")

    yearly = build_yearly_economics(results, champion_labels)
    write_csv(yearly, processed_dir / "wsop_yearly_economics_with_status.csv")

    heads_up_labels = build_headsup_labels(results, final_table, headsup_label_source, labels_dir)
    write_csv(heads_up_labels, labels_dir / "wsop_headsup_eventtime_labels.csv")

    # C) Outputs derived from labels + economics.
    summaries = build_summary_outputs(yearly, champion_labels, heads_up_labels)
    for filename, df in summaries.items():
        write_csv(df, processed_dir / filename)

    # D) Simulation.
    sim_players = build_simulated_player_cohort()
    write_csv(sim_players, processed_dir / "wsop_simulated_player_cohort.csv")

    # E) Expanded heads-up possibility from full results.
    top2_coverage, expanded_heads_up_base = build_expanded_headsup_from_full_results(results)
    write_csv(top2_coverage, processed_dir / "wsop_full_results_top2_coverage_check.csv")
    write_csv(expanded_heads_up_base, processed_dir / "wsop_full_results_expanded_heads_up_base.csv")

    if not args.skip_charts:
        make_charts(output_root, yearly, champion_labels, summaries["wsop_headsup_mix_counts.csv"], sim_players)

    print("\nRebuild complete.")
    print(f"Output root: {output_root.resolve()}")
    print("\nGenerated from the two Kaggle datasets directly:")
    print("  data/raw/wsop_main_event_results_1971-2025.csv")
    print("  data/raw/wsop_main_event_final_table_2001-2025.csv")
    print("  data/processed/wsop_dataset_reconciliation_detail.csv")
    print("  data/processed/wsop_dataset_reconciliation_summary.csv")
    print("  data/processed/wsop_full_results_top2_coverage_check.csv")
    print("  data/processed/wsop_full_results_expanded_heads_up_base.csv")
    print("\nGenerated from Kaggle + event-time label layer:")
    print("  data/labels/wsop_champion_eventtime_labels.csv")
    print("  data/labels/wsop_headsup_eventtime_labels.csv")
    print("  data/processed/wsop_yearly_economics_with_status.csv")
    print("  data/processed/wsop_era_champion_status_summary.csv")
    print("  data/processed/wsop_headsup_mix_by_year.csv")
    print("  data/processed/wsop_headsup_mix_counts.csv")
    print("  data/processed/wsop_uncertainty_stress_test.csv")
    print("  data/processed/wsop_key_metrics.csv")
    print("\nGenerated synthetically:")
    print("  data/processed/wsop_simulated_player_cohort.csv")
    print("\nCharts:")
    print("  outputs/charts/*.html")
    print("  outputs/charts/*.png if kaleido is installed")


if __name__ == "__main__":
    main()
